### ISSUE TITLE
Some icons are deprecated in the recently released nerd-fonts version 3, we should fix them

### ISSUE THREAD

**Issue by hehelego** [alexanderjeurissen/ranger_devicons#112]
- [x] I've read the [guidelines for Contributing](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/CONTRIBUTING.MD)

**Describe the bug**

Some popular icons are deprecated in [Github: Nerd Font v3.0.0 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0).  
I've spotted the following icons are not displaying correcty

 - PDF
 - PPT, PPTX
 - R (the statistical programming language)
 - vue

**To Reproduce**

1. Install a font with nerd-fonts version 3.0 patch.   
   For archlinux user, simply install a package in the `nerd-fonts` group e.g. `ttf-hack-nerd`
2. Configure your terminal emulator to use that font.
3. Install `ranger_devicons` following the instructions in `README.md`
4. Start ranger and navigate to a directory which contains some pdf files.

**Expected behavior**

You will see a blank character rather than a PDF file-format icon displaying on the first column.  

**Environment (please complete the following information):**
 - Arch linux with main thread kernel version 6.2.13
 - fish shell, version 3.6.1

**Ranger devicons (please complete the following information):**
 - `5bb1c32f649055c2d9143c8371c2bf06d5e574f7`
 - output of `exa --tree ~/.config/ranger`

 ```plaintext
.config/ranger
├── plugins
│  ├── __init__.py
│  └── ranger_devicons
│     ├── __init__.py
│     ├── CONTRIBUTING.MD
│     ├── devicons.py
│     ├── LICENSE
│     ├── LICENSE_NERDFONT
│     ├── README.md
│     └── screenshot.png
└── rc.conf
```

**Additional context**

- See also [github issues 1190 in nerd-fonts repo](https://github.com/ryanoasis/nerd-fonts/issues/1190)

**Comment by spcarluccio** [comment]
Will the changes be committed ?
When cloning the repo recently it still on 109

**Comment by alexanderjeurissen** [comment]
I just merged the PR from @prateekpunetha.

@spcarluccio can you confirm this resolves the issue ?

**Comment by spcarluccio** [comment]
I manually merged @Bekaboo PR and it fixed the issues.
