### ISSUE TITLE
Text to rc.conf not added properly

### ISSUE THREAD

**Issue by Patark** [alexanderjeurissen/ranger_devicons#20]
When installing with `make install` my rc.conf ends up looking like this:
```
set wrap_scroll true
set preview_images true
set preview_images_method w3m
set confirm_on_delete always
set show_hidden true
map <C-f> fzf_select
map <delete> delete# a plugin that adds file glyphs / icon support to Ranger:\n# https://github.com/alexanderjeurissen/ranger_devicons\ndefault_linemode devicons
```

**Comment by alexanderjeurissen** [comment]
@Patark Hmm that's interesting, can you share some more information about you're setup ? e.g. terminal emulater, operating system, other packages that you have installed etc. That will help in debugging this issue.

**Comment by Patark** [comment]
Sure thing. I'm running antergos. Here's a list of installed packages: https://gist.github.com/Patark/09c0c2964cd8756aaf26aa95011fac54

I've tried using Tilix, Alacritty, and xterm as well as using fish instead of bash, and the results are the same.

**Comment by glotzbam** [comment]
Same issue here. Plus after the lines in rc are corrected manually, ranger tells me
"Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime"

**Comment by alexanderjeurissen** [comment]
@glotzbam the later issue you mentioned `invalid linemode` was a bug in Ranger itself, and should be resolved in ranger versions later then 1.8.3.

@Patark thanks for providing more information, I'm currently really busy but when some time frees up I'll take a look at the info you provided.

**Comment by alexanderjeurissen** [comment]
@Patark can you checkout the branch `20/fix_test_added_to_rc_conf` ? and see if that fixes your issue ? (https://github.com/alexanderjeurissen/ranger_devicons/tree/20/fix_text_added_to_rc_conf)

**Comment by alexanderjeurissen** [comment]
@Patark closing this issue out, I merged PR #22 so if you update the plugin it should add the correct pretext in rc.conf. Feel free to reopen if this didn't resolve you're issue.

**Comment by Patark** [comment]
Just gave it a go. There's still a \n getting  added at to the default_linemode line as shown below:

# a plugin that adds file glyphs / icon support to Ranger:
# https://github.com/alexanderjeurissen/ranger_devicons
default_linemode devicons\n

I can see in the commit that the actual \n gets echoed out which i guess it shouldn't?

**Comment by alexanderjeurissen** [comment]
@Patark good find, not sure how that got in there, I committed a fix, can you verify it works as expected ?

**Comment by Patark** [comment]
Yep, looks good 👍
