### ISSUE TITLE
Document icon is randomly switching with char "Ò"

### ISSUE THREAD

**Issue by freed00m** [alexanderjeurissen/ranger_devicons#21]
Hi,

It's a really weird problem and it's the only icon it happens to yet.

It usually starts normally.

![2018-03-25-223300_921x519_scrot](https://user-images.githubusercontent.com/9461698/37879659-9141848a-307c-11e8-937d-bde1bb657523.png)

Then it's easily triggerproof way is with `set viewmode multipane` and increasing the font size back and forth.

This is before the font resize
![2018-03-25-223316_921x519_scrot](https://user-images.githubusercontent.com/9461698/37879674-baea7ea4-307c-11e8-8b9d-b2afcbbff596.png)

And this is after.
![2018-03-25-223326_921x519_scrot](https://user-images.githubusercontent.com/9461698/37879675-bd4c646e-307c-11e8-84ee-c75a02fd2433.png)

My question is, why is that? And what could possibly interfere, using suckless terminal?

Here is my fc-list
[fclist.txt](https://github.com/alexanderjeurissen/ranger_devicons/files/1845770/fclist.txt)

In terminal alacritty, it's not switching the character but it's always the character `Ò`.

**Comment by alexanderjeurissen** [comment]
Hi @freed00m Thanks for reporting this, I've also noticed the Documents icon being out of sync in Alacritty. I'm not sure what is causing this but it's something that recently broke. 

My first hunch is that it might have to do with the latest version of the patched NERD fonts, do you remember when you last updated you're NERD font ?

**Comment by freed00m** [comment]
@alexanderjeurissen  Sometime around 2 month ago, but the bug could have been there before. I just paid little attention to it.

**Comment by alexanderjeurissen** [comment]
@j-degreef noticed something similar in the issue I just linked. 

his latest comment: https://github.com/alexanderjeurissen/ranger_devicons/issues/19#issuecomment-375927444

> Hi,
> 
> Thanks for your explanation. I suspected it had nothing to do with ranger_devicons.
> I'm been working with double-byte characters (and RTL alignment) implementing chinese, corean, thai languages in a english software that was not written for them so I know the problem we can have with fonts...
> 
> I can confirm that it works ok with SauceCodePro NerdFont except for the Doc icon and the GoogleDrive icon from https://fontawesome.com/cheatsheet.
> But Fira, Fura, and a few others are not working properly for me, even after a clean install from git (both Ranger and Ranger_Devicons) and hours reading the Nerd font documentation.
> 
> What environment do you use ? It seems font rendering is not quite the same on PC and OSX. It's even not the same on VTE terminals, xterm or urxvt.
> Btw, would you share the font file you use so I can test it ?
> 
> BR,
> Jerome

I'm merging it in here so we can have a single discussion as I feel some of these issues might be linked.

**Comment by freed00m** [comment]
Not using ranger and it's probably terminal client rendering issue.
