### ISSUE TITLE
Feature Request: Colored icons

### ISSUE THREAD

**Issue by ad-si** [alexanderjeurissen/ranger_devicons#23]
It would be really color if there was an option to color the icons like in https://github.com/ryanoasis/vim-devicons

Any chance this gets implemented? :grin:

![](https://github.com/ryanoasis/vim-devicons/wiki/screenshots/v0.10.x/overall-screenshot.png)

**Comment by alexanderjeurissen** [comment]
Hi @ad-si Thanks for submitting this feature request. That looks pretty rad, I think we might be limited to the ranger colorschemes, but I'll see if this can be achieved using color escape codes and the likes.

**Comment by alexanderjeurissen** [comment]
initial results don't seem very promising.. escape codes don't get interpreted by ranger but get printed directly.

<img width="418" alt="Screenshot 2020-06-03 at 22 50 15" src="https://user-images.githubusercontent.com/1220084/83687806-99d59e00-a5ec-11ea-9f43-792a40a4de91.png">

**Comment by alexanderjeurissen** [comment]
I'll do some more investigation this weekend to see if I can get it to work.

**Comment by CallumHoward** [comment]
Did you manage to figure anything out for this?

**Comment by alexanderjeurissen** [comment]
@CallumHoward not yet. Looks like Ranger completely ignores color escape codes. Also the font color of the linemode seems to be defined in the theme meaning ranger likely does not support partial highlights. 

I'm open to suggestions and/or  a PR.

**Comment by ad-si** [comment]
Still relevant ;-)

**Comment by ad-si** [comment]
Uhm what? Why was it closed? What's the correct code word for the bot @alexanderjeurissen? 😅

**Comment by alexanderjeurissen** [comment]
Seems one needs to remove the "stale issue" label explicitly. 

For now I reopened the issue

**Comment by SuperSandro2000** [comment]
bump

**Comment by alexanderjeurissen** [comment]
Thanks for the bump @SuperSandro2000 

From my investigations it seems that this is not really feasible at this point in time.

Ranger does not support multi-colored output for its linemodes.

Font color for all text rendered in the linemode is defined by the 'theme'. This is a single color and does not support contextual coloring let alone multi-part color output.

As such, if people really want this feature I'd advise opening an issue upstream in the Ranger project.

**Comment by ad-si** [comment]
Still relevant 😉

**Comment by alexanderjeurissen** [comment]
The only way to get this working is if Ranger starts supporting ANSI escape codes / colors in line modes.
Currently changing the color of individual items is limited to color schemes.

ref: https://github.com/ranger/ranger/issues/169 
ref: https://github.com/ranger/ranger/issues/68

But those are limited in that highlighting takes place on a per line level.

@ad-si as the OP of this issue I urge you to create an issue upstream in the ranger project if this is something you really want. Without ranger supporting this there is nothing really that I can do.

**Comment by SuperSandro2000** [comment]
Bump

**Comment by UltiRequiem** [comment]
Bump Bump

**Comment by CallumHoward** [comment]
bump bump bump

**Comment by XuehaiPan** [comment]
I have created a PR to add ANSI escape codes support in the ranger browser column, which makes it possible for colored icons or partially highlighted texts. See ranger/ranger#2445.

**Comment by UltiRequiem** [comment]
bump bump bump bump

**Comment by UltiRequiem** [comment]
BUMP!

**Comment by UltiRequiem** [comment]
bump

**Comment by ad-si** [comment]
…

**Comment by CallumHoward** [comment]
I have been using @XuehaiPan's [PR branch](https://github.com/ranger/ranger/pull/2445) for 3 months now and it works without problem. I would love to see it reviewed and discussed so this cool feature can be merged and shared with everyone.
