### ISSUE TITLE
Icons don't show with patched fonts

### ISSUE THREAD

**Issue by bbaserdem** [alexanderjeurissen/ranger_devicons#28]
I can't see any icons on ranger. Unlike the other problems here, I don't see any icons.

I use FuraCode Nerd Font Mono, and termite. (Using archlinux packages from AUR) I have tried switching to SauceCodePro Nerd Font Mono, and I have tried multiple terminals (urxvt, kitty, st) and the icons are blank all throughout.
![2018-08-09_15 27 06](https://user-images.githubusercontent.com/19315586/43929336-654e9556-9be9-11e8-9f33-4601f1484458.png)

**Comment by alexanderjeurissen** [comment]
@bbaserdem thanks for reporting this.
Do utf-8 icons display in other parts of your terminal (meaning outside of ranger) ? a quick way to test this is executing the following and seeing if it renders any icon:
`echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"`

If icons are rendered when executing the command above, I likely need some more context to troubleshoot the issue. Can you tell me:
1. What ranger version you are using
2. the source and the point in time you downloaded the fonts
3. your terminal emulator version

**Comment by bbaserdem** [comment]
I can render the fonts outside of ranger just fine. I'm getting right triangle, +-. fork, arrow, X, colored lightning and an orb as glyphs.  

Ranger version is;
```
ranger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
Locale: None.None
```

Running `termite --version` outputs `termite v13`.

Running `ncursesw6-config --version` returns `6.1.20180127` (I assume ranger is an ncurses app?)

(I use Arch btw) I used the following AUR packages, and tested with multiple fonts. [nerd-fonts-complete](https://aur.archlinux.org/packages/nerd-fonts-complete/) [nerd-fonts-source-code-pro](https://aur.archlinux.org/packages/nerd-fonts-source-code-pro/) and [otf-nerd-fonts-fira-code](https://aur.archlinux.org/packages/otf-nerd-fonts-fira-code/) None of the fonts from the packages do work.

I also have problems with other terminal apps (ncmpcpp) not rendering glyphs, so I think this is more some rendering issue than specific to devicons. The problem persists accross terminals (kitty, urxvt, termite, st)

**Comment by alexanderjeurissen** [comment]
@bbaserdem ok thanks for providing version info, to make sure that devicons is loaded correctly, can you modify the following file `.config/ranger/devicons.py` and change the method defined at line 217 to:

```
def devicon(file):
  if file.is_directory: return  'D'
  return  'F'
```

then execute ranger again, and see if directories are prefixed with a `D` and files with `F` similar to the screenshot below:
![screen shot 2018-08-12 at 1 34 34 pm](https://user-images.githubusercontent.com/1220084/44001544-7d93d53e-9e34-11e8-9a85-dde92b914773.png)

This will help me confirm if the devicons plugin is loaded correctly and can render anything at all.

**Comment by bbaserdem** [comment]
Yes, I do get the letters before directories and files. Definitely not linked to devicons.

Strangest is, when I use vim, I see the glyphs just fine in the devicons.py

**Comment by bbaserdem** [comment]
So I found out the issue and fixed it. I had /etc/locale.gen configured and generated locale, but /etc/locale.conf was not configured. Doing that fixed the issue. Definitely not devicons fault.

Maybe a line at troubleshooting mentioning this could be a cause? Other than that I don't think further discussion is neccessary.

**Comment by lfilho** [comment]
Hey @bbaserdem could you share how you configured /etc/locale.conf and /etc/locale.gen? I don't have any of those files in my system. Thank you!

**Comment by bbaserdem** [comment]
I would suggest following through [this page](https://wiki.archlinux.org/index.php/Locale); i don't have access to my computer.
