### ISSUE TITLE
Does not work despite fonts being installed

### ISSUE THREAD

**Issue by sergarcia** [alexanderjeurissen/ranger_devicons#36]
I have SauceProCode as my terminal font and when I open devicons.py in vim I can see the symbols, however in ranger I only see additional empty space next to file/directory names after installing ranger_devicons. In other words I don't see the icons at all in ranger.  Also the `fc-list` command detects SauceProCode. I installed the fonts through the AUR.

**Comment by alexanderjeurissen** [comment]
can you try running `make uninstall`
Then pull the latest master and run `make install` again.

**Comment by sergarcia** [comment]
I figured out the problem, my locale configuration was bad and I fixed it by adding a couple of lines to my .bashrc. This also fixed the ranger icons.

**Comment by alexanderjeurissen** [comment]
@sergarcia glad to hear you managed to fix the problem. Can you share what lines you fixed so other people that might find this issue in the future can fix it themselves as well ?

**Comment by sergarcia** [comment]
When ranger started it would flash a message along the lines of "could not set locale ... expect encoding errors". There might be a log where this message can be clearly seen. I use Arch, and configured my locales with the defaults steps from their wiki, but some programs would still complaint about locales. So to finally solve that I added the following lines to my .bashrc
~~~
export LANG=en_US.UTF-8
export LC_MESSAGES="C"
~~~
Which solved my locale issues and made ranger_devicons work!

**Comment by alexanderjeurissen** [comment]
@sergarcia Thanks for sharing your resolution steps, hopefully people in the future will find it helpful in resolving their own environment. Happy holidays !

**Comment by scrouthtv** [comment]
Thanks for sharing. Helped me too
