### ISSUE TITLE
Is there any way to control how tight the spacing of the icon to text is?

### ISSUE THREAD

**Issue by planigan** [alexanderjeurissen/ranger_devicons#4]
The spacing is very tight on my box:

![image](https://cloud.githubusercontent.com/assets/478095/23836419/2be3eb6c-074e-11e7-80c4-317e95799898.png)

**Comment by alexanderjeurissen** [comment]
@planigan This can be controlled, by default a single space is included as spacing. 

see https://github.com/alexanderjeurissen/ranger_devicons/blob/master/devicons_linemode.py#L12

```
return devicon(file) + ' ' + file.relative_path
```

you can change that code to include two spaces, I myself have no spacing issues however, did you try using a smaller font ?

**Comment by planigan** [comment]
Thank you very much for this plugin and for spoon feeding me something I should have found for myself. I was in `devicons.py` adding/changing icons, but I hadn't looked in `devicons_linemode.py`. I hadn't tried messing with the font. It was a simple fix with what you pointed out.

Feel free to close this, or leave it open for others to find easier.

Thanks again.

**Comment by alexanderjeurissen** [comment]
np

**Comment by andys8** [comment]
@alexanderjeurissen I had the need for a similar option. Maybe there could be a way to make this configurable. I came up with this but there might be better solutions for configuration.

https://github.com/andys8/ranger_devicons/commit/3ae505cff08bc22808c814b1c0b0bcb4cdfb2422

Maybe you're interested in having this configuration.

![image](https://user-images.githubusercontent.com/13085980/80920298-27646a80-8d6f-11ea-8b23-bfd45902a6df.png)


![image](https://user-images.githubusercontent.com/13085980/80920311-3ba86780-8d6f-11ea-8bf1-c7a90b88b28a.png)

Font: Iosevka Nerd Font 14
