### ISSUE TITLE
Wrong icons for Dropbox and `.sh` files

### ISSUE THREAD

**Issue by fsquillace** [alexanderjeurissen/ranger_devicons#45]
Since one of the last changes (https://github.com/alexanderjeurissen/ranger_devicons/commit/81cb58b3d1ce4c36cd1f351f40ae4a13682849ae) I have noticed that the Dropbox folder and the `*.sh` files have wrong icons. Range shows a gear for the Dropbox folder whereas `*.sh` shows a `#` sign instead of the terminal character.

Is this an intentional change?

Thanks

**Comment by alexanderjeurissen** [comment]
This is not intentional, There is a PR out #48 to address the dropbox icon, feel free to submit a PR to fix the incorrect SH icon. If you don't get around to doing so I'll see if I have some time this weekend to address this issue.

**Comment by SuperSandro2000** [comment]
bump

**Comment by westofer** [comment]
Was the solution just changing an icon? it seemed too easy #68

**Comment by SuperSandro2000** [comment]
bump

**Comment by alexanderjeurissen** [comment]
closed by #68
