### ISSUE TITLE
Not working properly, there are ectangles next to icons

### ISSUE THREAD

**Issue by sdushantha** [alexanderjeurissen/ranger_devicons#49]
There are for some reason rectangles next to the icons, which cause the the icons to look a little messy. My guess is that it has to do something with the fonts that I am using. 
![Screenshot_19-06-03_at_18-58-15](https://user-images.githubusercontent.com/27065646/58822331-87bacb80-8637-11e9-89c2-e0fe78d845e5.png)

Terminal: kitty
Font used in terminal: Hack

**Comment by alexanderjeurissen** [comment]
Are you using the NERD font patched version of `Hack` ? 
e.g. https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack

**Comment by sdushantha** [comment]
No, I am using the `Symbols Nerd Font`
```bash
$ fc-list | grep "Nerd"
/home/siddharth/.local/share/fonts/Nerd_Font_Complete.ttf: Symbols Nerd Font:style=2048-em
```

The strange thing is that it worked perfectly on the terminal emulator `st`.
![Screenshot_19-06-14_at_08-06-50](https://user-images.githubusercontent.com/27065646/59486997-85e4d980-8e7b-11e9-9b4e-c4a66a1bba96.png)

**Comment by Mange** [comment]
Pretty sure it's this problem: https://github.com/ryanoasis/nerd-fonts/pull/297

**Comment by sdushantha** [comment]
Since that PR has not been merged, is there something I can do so that I can install the working font that you made?

**Comment by Mange** [comment]
No, not really. I have a copy of the font locally on another machine that I use right now.

Maybe you could ping that thread so I can get some assistance on it.

**Comment by sdushantha** [comment]
Is it possible to get a copy of the font file?

Yes, I can ping the thread :)

**Comment by alexanderjeurissen** [comment]
Seeing as this seems to be a nerd-fonts issue I'm closing this out for now.

The aforementioned issues in the nerd fonts repository also have since been closed. If this issue is still present feel free to reopen.
