### ISSUE TITLE
PR with new config filenames

### ISSUE THREAD

**Issue by j-degreef** [alexanderjeurissen/ranger_devicons#5]
Hello,
I have a PR nearly ready with a newspaper icon for log files and several more config file names but I just discover that video files are ignored right now.
I'll try to include these in my PR.
Should be ready by tomorrow or monday.
BR, Jérôme

**Comment by j-degreef** [comment]
+ any idea for an icon for .xml files ? I'm thinking of the http one but we could maybe find a better one.

**Comment by j-degreef** [comment]
I agree ;)

**Comment by alexanderjeurissen** [comment]
Thanks again for reporting this issue. I just merged PR #6
