### ISSUE TITLE
Strange behaviour with icons

### ISSUE THREAD

**Issue by kharnox** [alexanderjeurissen/ranger_devicons#50]
Hi. 

First of all, thanks for the awesome work, keep it up!

So, here is the issue I am facing: 
When opening ranger, some icons do not show: it seems to occur mostly on folders of "unknown types" (so, folders which aren't defined in the devicons.py) .
Also, some icons show only when the cursor is on them. 

![2019-07-18-212232_570x259_scrot](https://user-images.githubusercontent.com/37575235/61485785-56f1e400-a9a2-11e9-9930-576f0da7753e.png)
![2019-07-18-212250_528x236_scrot](https://user-images.githubusercontent.com/37575235/61485786-56f1e400-a9a2-11e9-81a2-67abeaf52bc2.png)
![2019-07-18-212301_515x227_scrot](https://user-images.githubusercontent.com/37575235/61485787-56f1e400-a9a2-11e9-8238-7d0b149c28c4.png)

I am currently using urxvt v9.22 .
Usinf DejaVu Sans Mono for Powerline and DejaVu Sans Mono Nerd Font. 
using the command `echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"` displays all icons properly. Also, since most of the icons are displayed in a way or another, I assume this is not related to the font itself ?

Regards, 
Kharnox

**Comment by krvkir** [comment]
I have the same problem with DroidSansMono Nerd Font on urxvt 9.22, but icons work fine on Xfce terminal with the same font.

**Comment by kharnox** [comment]
Quick update -- 

Seems like a couple of Nerds fonts aren't correctly working (at least within URxvt)
Switched to FureCode Nerd Font and now everything is working as expected. 

Closing the issue as it is resolved
