### ISSUE TITLE
Icons not displaying at all 

### ISSUE THREAD

**Issue by GreyDireWolf** [alexanderjeurissen/ranger_devicons#55]
I use urxvt for terminal and Sauce Code Nerd Font from nerd fonts but the icons are not displayed in ranger at all. I tried it on termite still doesn't work
![2020-01-27_00-05](https://user-images.githubusercontent.com/13380243/73139917-2699a980-4099-11ea-8335-3ce71dfff916.png)

**Comment by aniru3-otaku** [comment]
After installing the devicons using experimental method, cd into that directory & run:
`make install`.
It fixed it for me.

**Comment by thexavier666** [comment]
> After installing the devicons using experimental method, cd into that directory & run:
> `make install`.
> It fixed it for me.

This should be mentioned in the readme

**Comment by GreyDireWolf** [comment]
@aniru3-otaku That didn't work for me

**Comment by thexavier666** [comment]
@GreyDireWolf Did you install the patched version of the fonts?

**Comment by aniru3-otaku** [comment]
@GreyDireWolf u need patched font for it to work

go to https://www.nerdfonts.com/font-downloads & download ur favorite font, place it into ~/.local/share/fonts/ and run `fc-cache`
after that configure ur terminal to use that font & u r all set :)

I can confirm that Sauce Code Nerd Font shows icons on termite:
![2020-02-12-134840_1520x1039_scrot](https://user-images.githubusercontent.com/60726339/74316128-e7f53600-4d9e-11ea-9de9-8816c3ba46cb.png)

**Comment by GreyDireWolf** [comment]
@aniru3-otaku still didn't work for me 
![ranger](https://user-images.githubusercontent.com/13380243/74345946-d75fb280-4dd4-11ea-92b5-4a63c4767947.png)

**Comment by jeffmhubbard** [comment]
Have tried any other fonts besides SauceCodePro? Also, are you using the repo urxvt? Try rxvt-unicode-cvs-patched-wideglyphs from AUR.

**Comment by thexavier666** [comment]
Can you tell us exactly where you have placed the plugin? @GreyDireWolf

**Comment by GreyDireWolf** [comment]
@jeffmhubbard I tried Hack and some other fonts. `rxvt-unicode-cvs-patched-wideglyphs` didn't work. @thexavier666 I placed the plugin in `~/.config/ranger/plugins` as mentioned in README

**Comment by aniru3-otaku** [comment]
What's the output when u run `make install` in ranger_devicons folder? Also, check ur plugins folder under ranger's configuration.
It should look something like this...
![2020-02-13-154918_1920x1079_scrot](https://user-images.githubusercontent.com/60726339/74424748-86a19580-4e78-11ea-9be8-c86e6d7910de.png)

**Comment by GreyDireWolf** [comment]
@aniru3-otaku my configuration looks same as yours. There is some space before name of the file/folder after installing the plugin. Here before and after installation screenshots
![without](https://user-images.githubusercontent.com/13380243/74447694-ca5bc580-4e9f-11ea-942f-22703fca2a76.png)
![with](https://user-images.githubusercontent.com/13380243/74447703-cd56b600-4e9f-11ea-84d7-b06872a50c44.png)

**Comment by aniru3-otaku** [comment]
ok so do one thing for me, open ~/.config/ranger/plugins/devicons.py. After that, change `if file.is_directory: return dir_node_exact_matches.get(file.relative_path, '')` (on 272 line) to something like `if file.is_directory: return dir_node_exact_matches.get(file.relative_path, 'F')`.

save it and open ranger, see if u can see the F word (lol) like here:
![2020-02-14-164820_745x360_scrot](https://user-images.githubusercontent.com/60726339/74526722-f9c70c80-4f49-11ea-82d7-d48eb649075c.png)

**Comment by GreyDireWolf** [comment]
@aniru3-otaku 
![F](https://user-images.githubusercontent.com/13380243/74659776-eff81000-51ba-11ea-861e-d904e119c6b8.png)

**Comment by jeffmhubbard** [comment]
That should indicate that the plugin is working correctly. Are you able to see glyphs/icons in other terminal apps? What does `echo $'\ue62b'` show?

**Comment by GreyDireWolf** [comment]
@jeffmhubbard Thanks for the hint. I didn't  properly setup locale on my system. Setting up the locale fixed the issue

**Comment by GreyDireWolf** [comment]
Closed #55
