### ISSUE TITLE
only Music dir not work

### ISSUE THREAD

**Issue by zdmgmail** [alexanderjeurissen/ranger_devicons#56]
![04-05_08:15:55](https://user-images.githubusercontent.com/50515839/78463947-d7659a00-7715-11ea-9687-fc55d4cd6985.png)

```
~ » uname -a                                                                                                                                                         zdm@ar
Linux ar 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux

pacman -S nerd-fonts-complete
yay -S nerd-fonts-source-code-pro

git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons

make install
```

why Music devicons is ".", Is there any solution ?

**Comment by Mange** [comment]
In your screenshot it looks like "Documents" is also wrong. Looks like a font loading issue.

Have you told your terminal to use the patched font?

Secondly, try logging out and in again. That should rebuild your while cache.

**Comment by zdmgmail** [comment]
> In your screenshot it looks like "Documents" is also wrong. Looks like a font loading issue.
> 
> Have you told your terminal to use the patched font?
> 
> Secondly, try logging out and in again. That should rebuild your whole font cache.

I reboot but still problem , the termminal  alacritty and urxvt both have problem

alacritty:

![04-05_15:07:56](https://user-images.githubusercontent.com/50515839/78469006-6c38b980-774f-11ea-9a6e-5fe7f6301be6.png)

uxrxvt:

![04-05_15:07:41](https://user-images.githubusercontent.com/50515839/78469004-680c9c00-774f-11ea-8f0f-4c4c3b6681da.png)

I haven't told the terminal use patch font, but in the past I used fedora and alacritty , that worked correctly

**Comment by zdmgmail** [comment]
> > In your screenshot it looks like "Documents" is also wrong. Looks like a font loading issue.
> > Have you told your terminal to use the patched font?
> > Secondly, try logging out and in again. That should rebuild your whole font cache.
> 
> I reboot but still problem , the termminal alacritty and urxvt both have problem
> 
> alacritty:
> 
> ![04-05_15:07:56](https://user-images.githubusercontent.com/50515839/78469006-6c38b980-774f-11ea-9a6e-5fe7f6301be6.png)
> 
> uxrxvt:
> 
> ![04-05_15:07:41](https://user-images.githubusercontent.com/50515839/78469004-680c9c00-774f-11ea-8f0f-4c4c3b6681da.png)
> 
> I haven't told the terminal use patch font, but in the past I used fedora and alacritty , that worked correctly

these two pictures should be swap

> > In your screenshot it looks like "Documents" is also wrong. Looks like a font loading issue.
> > Have you told your terminal to use the patched font?
> > Secondly, try logging out and in again. That should rebuild your whole font cache.
> 
> I reboot but still problem , the termminal alacritty and urxvt both have problem
> 
> alacritty:
> 
> ![04-05_15:07:56](https://user-images.githubusercontent.com/50515839/78469006-6c38b980-774f-11ea-9a6e-5fe7f6301be6.png)
> 
> uxrxvt:
> 
> ![04-05_15:07:41](https://user-images.githubusercontent.com/50515839/78469004-680c9c00-774f-11ea-8f0f-4c4c3b6681da.png)
> 
> I haven't told the terminal use patch font, but in the past I used fedora and alacritty , that worked correctly

these two pictures should be swaped

**Comment by zdmgmail** [comment]
may be nerd-font not intall correct? but I used these

```
	git clone https://github.com/ryanoasis/nerd-fonts ~/.nerd-fonts
	cd .nerd-fonts
	sudo ./install.sh

pacman -S nerd-fonts-complete
yay -S nerd-fonts-source-code-pro


```
