### ISSUE TITLE
Invalid linemode: devicons

### ISSUE THREAD

**Issue by mybigman** [alexanderjeurissen/ranger_devicons#64]
No icons shown and with the latest download I get the following error as soon as I exit ranger.

```
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime
```
OS: fedora 32
Terminal: kitty

**rc.conf**
```
set show_hidden true
default_linemode devicons
```

**Comment by alexanderjeurissen** [comment]
Hi, can you describe how you installed this library ?

also can you show me the tree output of your ranger directory ?

e.g. `dnf install tree` then `tree <ranger_path>`

**Comment by diandianti** [comment]
> Hi, can you describe how you installed this library ?
> 
> also can you show me the tree output of your ranger directory ?
> 
> e.g. `dnf install tree` then `tree <ranger_path>`

My ranger has same problem, I just git clone this repo and copy the files into ~/.config/ranger/plugin
and file tree is:
`.
├── bookmarks
├── commands_full.py
├── commands.py
├── history
├── plugins
│   ├── devicons_linemode.py
│   ├── devicons_linemode.pyo
│   ├── devicons.py
│   ├── devicons.pyo
│   ├── __init__.py
│   └── __init__.pyo
├── rc.conf
├── rifle.conf
├── scope.sh
└── tagged
`

**Comment by Alexey104** [comment]
Same problem on Arch with commits using new install method(later than f0b8fc2):
`Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime`

Moving *.py files to the root of plugins directory solves the problem:
`mv -fv ~/.config/ranger/plugins/ranger_devicons/*.py ~/.config/ranger/plugins` #Works fine now

**Comment by negativeExponent** [comment]
worked fine on my end without modifications using default rc.conf

![ranger](https://user-images.githubusercontent.com/54053706/88366816-bd32f300-cdbc-11ea-8b31-02af966c5ce5.png)

**Comment by Alexey104** [comment]
For me the problem was `/usr/lib/python3.8/site-packages/ranger/core/main.py` file. A long time ago I made some modifications in that file and saved the modified version as a backup for further usage. But that file was modified in newer ranger versions, and after replacing it with the default one everything is working fine. So, if you have `Invalid linemode` error and are using any old ranger configs, just try to delete them and use the defaults instead:
```
> Please note that configuration files may change as ranger evolves.
  It's completely up to you to keep them up to date.
```

**Comment by mybigman** [comment]
Moving the files out of the ```ranger_devicons``` works as expected but still fails in its own directory.

<img width="264" alt="Screen Shot 2020-07-25 at 12 53 54 pm" src="https://user-images.githubusercontent.com/1289916/88447387-ff6c3b00-ce75-11ea-8689-8e4fcc6592cb.png">

**Comment by magalhaesm** [comment]
Instead moving files, try just make symlinks.

ln -sf ~/.config/ranger/plugins/ranger_devicons/__init__.py ~/.config/ranger/plugins/__init__.py
ln -sf ~/.config/ranger/plugins/ranger_devicons/devicons.py ~/.config/ranger/plugins/devicons.py

This works fine for me.

**Comment by alexanderjeurissen** [comment]
cloning the plugin in the `~/.config/ranger/plugins` directory should work. this should result in a tree like this:

```
.
├── plugins
│   ├── __init__.py
│   ├── __init__.pyo
│   └── ranger_devicons
│       ├── LICENSE
│       ├── LICENSE_NERDFONT
│       ├── README.md
│       ├── __init__.py
│       ├── __init__.pyo
│       ├── devicons.py
│       ├── devicons.pyo
│       └── screenshot.png
└── rc.conf 
```

Make sure you are running the latest version of ranger and the error should not show up.

**Comment by rivalak** [comment]
> Instead of moving files, try to make symlinks.
> 
> `ln -sf ~/.config/ranger/plugins/ranger_devicons/__init__.py ~/.config/ranger/plugins/__init__.py`
> `ln -sf ~/.config/ranger/plugins/ranger_devicons/devicons.py ~/.config/ranger/plugins/devicons.py`
> 
> This works fine for me.

This solution works fine for me too.
