### ISSUE TITLE
keeping a linemode with devicons

### ISSUE THREAD

**Issue by elig0n** [alexanderjeurissen/ranger_devicons#65]
how can I keep both a default linemode (i.e. filename, sizehumanreadblemtime) and devicons together ?

**Comment by alexanderjeurissen** [comment]
by not specifying `devicons` as the default line mode, and manually invoking the devicons line mode whenever you want to use it.

e.g.

```
default_line_mode filename
```

then either manually invoke `:linemode devicons` or create a mapping if you frequently switch:

```
map Mf linemode filename
map Mi linemode fileinfo
map Md linemode devicons
```
