### ISSUE TITLE
Install script appends `default line mode entry` even if it already exists

### ISSUE THREAD

**Issue by alexanderjeurissen** [alexanderjeurissen/ranger_devicons#7]
When running 

```
$ make install
```

The install script appends an entry to the ranger configuration to use the ranger_devicons mode by default. However the install script currently isn't aware if this line is already present. This results in multiple entries when updating for example.

There are several possible solutions to this:

- Instead of copying the files using `install` we could symlink them to the correct locations, resulting in the end user only having to pull the latest changes and the plugin is up to date.
- Introduce a `update` command in the makefile that gets the latest git changes and replaces the old plugin files with the new ones.

**Comment by echuraev** [comment]
@alexanderjeurissen it was fixed in my PR #8

**Comment by alexanderjeurissen** [comment]
@echuraev thanks, I'll make sure to close this issue as part of PR #8
