### ISSUE TITLE
[Kitty] Ranger does not display devicons

### ISSUE THREAD

**Issue by tbrodbeck** [alexanderjeurissen/ranger_devicons#70]
#### Runtime Environment

- Operating system and version: macOS 14.01
- Terminal emulator and version: kitty 0.19.2
- Ranger version/commit: ranger version: ranger 1.9.3
- Python version: 2.7.16 (default, Oct 30 2020, 02:15:49) [GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri
- Locale: None.None
- shell: zsh 5.8 (x86_64-apple-darwin20.0) 

#### Current Behavior
When using kitty the devicons (https://github.com/alexanderjeurissen/ranger_devicons) the icons are sometimes shown and sometimes not. Instead there are those characters:
![problem](https://user-images.githubusercontent.com/24418160/100446102-7d538380-30ae-11eb-85d6-b23d0feaf8b7.jpg)

#### Expected Behavior
Display devicons to the left of files and directories.

#### Context

If I start `kitty` from another terminal (not kitty), the devicons are shown as expected. 

#### Steps to reproduce
1. Install `alexanderjeurissen/ranger_devicons`
2. Open kitty
3. type ranger

This is a mirror of https://github.com/ranger/ranger/issues/2169. I post it here in case you can help me debug the ranger devicon display engine.

**Comment by milkias17** [comment]
I use kitty as my terminal emulator and everything works fine. What is the terminal font you are using right now? If the font you are using is not patched with nerd font, it wont work.

**Comment by tbrodbeck** [comment]
This issue was from kitty and it is fixed by now (https://github.com/ranger/ranger/issues/2169)
