### ISSUE TITLE
Plugin overwrites "filename" linemode

### ISSUE THREAD

**Issue by potamides** [alexanderjeurissen/ranger_devicons#71]
**Describe the bug**
When the plugin is installed the filename linemode behaves the same way as the devicons linemode.

**To Reproduce**
1. Install plugin
2. specify filename linemode (e.g. through `default_linemode filename` in `rc.conf`)
3. devicon glyphs are shown, which is different from the default behavior

**Additional context**
It looks like the filename linemode gets overwritten in [\_\_init\_\_.py](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/__init__.py#L16). Removing the affected class solves the problem for me. I apologize if this is intended behavior, however to me it doesn't make sense to make the devicons and filename linemodes behave the same way.

**Comment by alexanderjeurissen** [comment]
@potamides Thanks for submitting this issue.

Nice find, this is not intentional. I'll go ahead and rectify this.
