### ISSUE TITLE
audio file icon not working properly

### ISSUE THREAD

**Issue by Mirai009** [alexanderjeurissen/ranger_devicons#74]
![gscreenshot_2021-02-05-153939](https://user-images.githubusercontent.com/76122563/107047925-4392ad80-67c0-11eb-85b3-ff57b327b46e.png)

**Comment by alexanderjeurissen** [comment]
Please refer to the [guidelines for contributing](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/CONTRIBUTING.MD) and the [bug report issue template](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Given that we only recently started enforcing the issue template, and bug report guidelines I'll keep this issue open for now.**

The icon seems to work properly on my side on the latest `main` branch:

<img width="1609" alt="Screen Shot 2021-03-04 at 1 06 35 PM" src="https://user-images.githubusercontent.com/1220084/109979674-6ea8e800-7cff-11eb-99e6-477d8e93f63e.png">

**Please anwer all questions listed in the linked issue template**

**Comment by Mirai009** [comment]
turns out the problem was the font changed it from source code pro to fira code and it worked
