### ISSUE TITLE
Made open folders display open folder icon, 1 LOC change

### ISSUE THREAD

**Issue by dnnis** [alexanderjeurissen/ranger_devicons#87]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, just a mere visual difference

**Describe the solution you'd like**
Wrote the below code on the end of the file of the plugin:

`def devicon(file):
  if file.realpath == os.getcwd(): return dir_node_exact_matches.get(file.relative_path, '')
  elif file.is_directory: return dir_node_exact_matches.get(file.relative_path, '')
  return file_node_exact_matches.get(os.path.basename(file.relative_path), file_node_extensions.get(file.extension, ''))
`

**Describe alternatives you've considered**
This does not seem to be terribly difficult to implement, I don't know if my code is the most efficient though.

**Additional context**
The code on my terminal:
![code_improve](https://user-images.githubusercontent.com/57800665/115231270-09c61780-a11e-11eb-89d3-b1acbd0f9529.png)
The effect it had:
![ranger_dev_plus](https://user-images.githubusercontent.com/57800665/115231306-134f7f80-a11e-11eb-9079-a29575a1aa59.png)

**Comment by jiud** [comment]
@alexanderjeurissen
 I am tagging you to see this, sorry for not following the template completely+tagging you, but tagging you is better than reposting the same issue I guess.
Thank you

**Comment by alexanderjeurissen** [comment]
@jiud np, I'll take a look thanks for pinging me

**Comment by nionios** [comment]
This is still relevant :)

**Comment by nionios** [comment]
Is this still relavant? :)
