### ISSUE TITLE
Blocks displaying instead of icons

### ISSUE THREAD

**Issue by FireAntJoe** [alexanderjeurissen/ranger_devicons#9]
I get these little blocks instead of icons when in ranger. I have python installed and nerd-fonts-git installed from the AUR.

**Comment by alexanderjeurissen** [comment]
@FireAntJoe That means that ranger can't find the glyphs that are used in this plugin. 

My first guess would be that the nerd-fonts font is not set as the default font for your terminal.
If however, your sure that you installed the nerd font correctly, and that you set the nerd font as the default font for rendering text in your terminal, then you could try manually installing the nerd font as listed on Github:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Regular

It's the exact same nerd font I'm using and thus should work, can you confirm the above ?

**Comment by FireAntJoe** [comment]
In my termite config .config I have the following line
`font = nerd-fonts 9` so as far as I know that should work. Nerd-fonts is installed as far as I know because otherwise my airline in my zsh wouldn't work but since it does and all icons display I assume that is not the issue.

**Comment by alexanderjeurissen** [comment]
Ok, thanks for clarifying that. To confirm that the nerd font is behaving correctly (and figure out if it's a ranger issue) could you open the devicons.py file `https://github.com/alexanderjeurissen/ranger_devicons/blob/master/devicons.py` in vim or just `cat` to print out it's contents.

If blocks show up in that case as well, could you try using the exact font that I listed ?

**Comment by alexanderjeurissen** [comment]
@FireAntJoe did you happen to have time to look into my suggestions ? Do you still have the problem you described earlier ?

**Comment by FireAntJoe** [comment]
It worked thanks man been a busy week

**Comment by alexanderjeurissen** [comment]
ok, I'll close this issue for now then. If you have any issues with the patched nerd fonts please in the future please redirect them to https://github.com/ryanoasis/nerd-fonts
