### ISSUE TITLE
Invalid linemode: devicons - Icons not showing

### ISSUE THREAD

**Issue by Head0nF1re** [alexanderjeurissen/ranger_devicons#93]
- [X] I've read the [guidelines for Contributing](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/CONTRIBUTING.MD)

**Describe the bug**
- Installed `ranger` from package manager
- Cloned `ranger_devicons`  into **~/.config/ranger/plugins**
- Moved `devicons.py` to **~/.config/ranger** and  `__init__.py` to **~./config.ranger/plugin** because I saw this issue: #64 
- Added `default_linemode devicons` to **~/.config/ranger/rc.conf**
- I have Hack Nerd fonts installed and can see the icons in **devicons.py**

Even tho it seems all is right, when I launch ranger no icons appear and it give the follow error:

`Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime`

When I do `ranger --debug`:

```
ranger version: ranger 1.9.3
Python version: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Locale: pt_PT.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 119, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 471, in load_settings
    fm.source(custom_conf)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 408, in source
    self.execute_console(line)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 271, in execute_console
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 553, in execute
    self.fm.notify(
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 177, in notify
    raise Exception(str(obj))
Exception: Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Environment**
 - OS: ArchLinux (5.14.3-arch1-1)
 - shell: bash
 - shell version: 5.1.8
- Terminal emulator: Alacritty

**Ranger devicons**
 - version / commit: HEAD
 - output of `tree ~/.config/ranger`:

```
ranger
├── commands_full.py
├── commands.py
├── devicons.py
├── plugins
│   ├── __init__.py
│   ├── __init__.py_
│   ├── __pycache__
│   │   ├── devicons.cpython-39.opt-1.pyc
│   │   └── __init__.cpython-39.opt-1.pyc
│   └── ranger_devicons
│       ├── CONTRIBUTING.MD
│       ├── LICENSE
│       ├── LICENSE_NERDFONT
│       ├── __pycache__
│       │   ├── devicons.cpython-39.opt-1.pyc
│       │   └── __init__.cpython-39.opt-1.pyc
│       ├── README.md
│       └── screenshot.png
├── rc.conf
├── rifle.conf
└── scope.sh
```

**Comment by sohorx** [comment]
I do not have time to look into it but... 

It seems to mean that its because of an error in the code merged #92 .
so comment everything about xdg configs and please, move your `devicons.py` into the `/plugins/ranger_devicons` (otherwise you will have an import error) and you should be fine.

**Comment by Head0nF1re** [comment]
> so comment everything about xdg configs and please, move your devicons.py into the /plugins/ranger_devicons (otherwise you will have an import error) and you should be fine.

@sohorx I tried to place the files in different ways before but didn't work. The problem like you said is the commit made after #92, but also needed to place both **__init__.py** and **devicons.py** in **~/.config/ranger/plugins** . Or, it also works creating a directory named "**devicons**" inside **~/.config/ranger/plugins** and place both files there. Or renaming the folder **ranger_devicons** into **devicons**.

I suggest adding to the README this additional information to prevent future issues related to this, even if the XDG issue gets fixed the placement of the files will still be an issue.

Thanks for the answer!

**Comment by aprowe** [comment]
Huh I tried all this and I still can't get them to work. Tried all sorts of renaming and I still get 
```
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime
```

**Comment by ohnomonkey** [comment]
Same here. I've tried all of the various suggestions and it continues to fail with the 'invalid linemode' error as described above by aprowe.

**Comment by nPHYN1T3** [comment]
Sadly this is not stale...
Exception: Invalid linemode: devicons
ranger version: ranger 1.9.3
Python version: 3.12.5 (main, Aug  9 2024, 08:20:41) [GCC 14.2.1 20240805]
