### ISSUE TITLE
Wrong icons being displayed in home folder and upon selection

### ISSUE THREAD

**Issue by stpnwf** [alexanderjeurissen/ranger_devicons#99]
- [x] I've read the [guidelines for Contributing](https://github.com/alexanderjeurissen/ranger_devicons/blob/main/CONTRIBUTING.MD)

**Describe the bug**
Documents and Public folder icons display weird characters instead of chosen icons. Changing them has no effect.

![2021-11-11T22:50:52-03:00-cropped](https://user-images.githubusercontent.com/81482539/141396364-17ff1d3c-05ee-4d8e-bbee-aec50a75da28.jpg)

Edit:
This also happens to some icons when they are highlighted: 

![2021-11-12T00:09:38-03:00-cropped](https://user-images.githubusercontent.com/81482539/141402923-53f2eb18-4686-473c-a4b9-bebe6d8abda8.jpg)

Unlike the first case, this seems to be a problem with certain icons only. I have noticed it to be a problem with these icons: 
 and 

Bonus question: how can I change the icon of files that don't have extensions/files whose extensions are not "supported"? (I know new file extensions can be added to devicons.py though)

 - OS + version: Zorin OS 16 (Ubuntu 20.04 based)
 - shell: bash 5.0.17
 - terminal: alacritty
 - font: Liga SFMono Nerd Font

**Ranger devicons (please complete the following information):**
 - version / commit: 1194161
 - output of `tree ~/.config/ranger`:
├── commands.py
├── devicons.py
├── plugins
│   ├── devicons_linemode.py
│   ├── __init__.py
│   └── __pycache__
│       ├── devicons_linemode.cpython-38.opt-1.pyc
│       ├── devicons_linemode.cpython-39.opt-1.pyc
│       ├── __init__.cpython-38.opt-1.pyc
│       └── __init__.cpython-39.opt-1.pyc
├── __pycache__
│   ├── devicons.cpython-38.opt-1.pyc
│   └── devicons.cpython-39.opt-1.pyc
├── rc.conf
└── scope.sh

I grabbed ranger dotfiles from /r/unixporn. I have replaced devicons.py with the latest version. Unsure if this issue stems from another file in that folder.

**Comment by ohmyhub** [comment]
See my comment on a similar issue.
https://github.com/alexanderjeurissen/ranger_devicons/issues/100#issuecomment-984355990
